#!/bin/sh

if [ $# = 0 ]; then
   blink_pid=$(ps x | grep -E '\./blink|bin/blink' | grep -v grep | head -1 | awk '{print $1}')
else
   blink_pid=$1
fi

gdb --batch --eval-command="attach $blink_pid" --eval-command="thread apply all bt"

