.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH Blink 1 "July 16, 2010" "" "Blink"

.SH NAME
blink \- Fully featured, easy to use SIP client with a Qt based UI

.SH DESCRIPTION
Find the complete 
.B Blink 
features and information at http://icanblink.com
