.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH blink-settings 1 "August 13, 2010" "" "blink-settings"

.SH NOMBRE
blink-settings \- script to modify Blink settings

.SH DESCRIPCION
Complete commands description can be found at 
.LP
http://icanblink.com/blink-qt-beta.phtml
