.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH Blink 1 "Feb 09, 2017" "" "Blink"

.SH NAME
blink \- Fully featured, easy to use SIP client with a Qt based UI

.SH DESCRIPTION
The complete list of features and more information about
.B Blink
can be found at \%http://icanblink.com/
